TicketPrice: 
  ages: 
    sinceSenior: 60
    limitBaby: 4
    limitChildren: 12
  prices: 
    senior: 12
    baby: 0
    children: 8
    normal: 16
    discount: 10
  coefficient: 
    halfDay: .5

UnavailableDate: 
  week: 
   sunday: 'sun'
   tuesday: 'tue'

EntriesLimit: 1000

Holidays:
  newYear: '01/01'
  laborDay: '01/05'
  victoire: '08/05'
  bastilleDay: '14/07'
  ascension: '15/08'
  toussaint: '01/11'
  armistice: '11/11'
  christmas: '25/12'





