TicketPrice: 
  ages: 
    sinceSenior: 60
    limitBaby: 4
    limitChildren: 12
  prices: 
    senior: 12
    baby: 0
    children: 8
    normal: 16
    discount: 10
  coefficient: 
    halfDay: .5


closedDay: 
  - Sunday
  - Tuesday

Holidays:
  - '01/01'
  - '01/05'
  - '08/05'
  - '14/07'
  - '15/08'
  - '01/11'
  - '11/11'
  - '25/12'

EntriesLimit: 1000

BookingHourMax: 22

parameters:
  stripe_public_key: 'zrgerhgerher'








