TicketPrice: 
  ages: 
    sinceSenior: 60
    limitBaby: 4
    limitChildren: 12
  prices: 
    senior: 12
    baby: 0
    children: 8
    normal: 16
    discount: 10
  coefficient: 
    halfDay: .5

UnavailableDate: 
  week: 
    - sun
    - tue

EntriesLimit: 1000

Holidays:
    // Dates fixes
    - mktime(0, 0, 0, 1, 1, $year),  // 1er janvier
    - mktime(0, 0, 0, 5, 1, $year),  // Fête du travail
    - mktime(0, 0, 0, 5, 8, $year),  // Victoire des alliés
    - mktime(0, 0, 0, 7, 14, $year),  // Fête nationale
    - mktime(0, 0, 0, 8, 15, $year),  // Assomption
    - mktime(0, 0, 0, 11, 1, $year),  // Toussaint
    - mktime(0, 0, 0, 11, 11, $year),  // Armistice
    - mktime(0, 0, 0, 12, 25, $year),  // Noel

    // Dates variables
    - mktime(0, 0, 0, $easterMonth, $easterDay + 1, $easterYear), // Lundi de Paques
    - mktime(0, 0, 0, $easterMonth, $easterDay + 39, $easterYear), // Ascension
    - mktime(0, 0, 0, $easterMonth, $easterDay + 50, $easterYear), // Lundi de Pentecôte