parameters:
  stripe_public_key: 'pk_test_51HeLh9Ahufd1YJu1upvLnvCRa7zfk6gO6liv68Lxshy5wUv90Tt7W2oiNmNwHocTW0QUJG0TuELRquHfj5VoDt1S00ZiDe61WY'
  stripe_secret_key: 'sk_test_51HeLh9Ahufd1YJu1368gsHaeysM6kOR2UkCERDqYGrqCj4CLPQcSpBFUaKxvtxsRUxlNHHW3KDFyd30rEkiJs8my00P9En7Ihd'